apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: tektoncd-operator
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace
